# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from viewItem import Ui_viewItemWindow
from newItem import Ui_newItem
from viewEmployee import Ui_viewEmployee
from allClientsupdate import Ui_viewClients
from newInvoice import Ui_newInvoiceWindow
from payment import Ui_paymentWindow
from viewInvoicesAll import Ui_allInvoicesView
from purchaseOrder import Ui_purchaseOrder
from allPurchaseOrderView import Ui_allPurchaseOrderView
from payPurchaseOrder import Ui_payPurchaseOrder
from allPaymentsOfPurchaseOrders import Ui_allPaymetsOfPurchaseOrders
from detailPaymentsOfPurchaseOrders import Ui_allPaymetsOfPurchaseOrders as allOrder
from allSuppliers import Ui_viewSuppliers
from returnWindow import Ui_returnWindow


class Ui_CentralWindow(object):
    def setupUi(self, CentralWindow):
        CentralWindow.setObjectName("CentralWindow")
        CentralWindow.resize(785, 552)
        CentralWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(CentralWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.centralPic = QtWidgets.QLabel(self.centralwidget)
        self.centralPic.setText("")
        self.centralPic.setPixmap(QtGui.QPixmap("../Images/Quran.png"))
        self.centralPic.setScaledContents(True)
        self.centralPic.setObjectName("centralPic")
        self.verticalLayout.addWidget(self.centralPic)
        CentralWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CentralWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 785, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuAccounts = QtWidgets.QMenu(self.menuMenu)
        self.menuAccounts.setObjectName("menuAccounts")
        self.menuSales = QtWidgets.QMenu(self.menuMenu)
        self.menuSales.setObjectName("menuSales")
        self.menuPurcahses = QtWidgets.QMenu(self.menuMenu)
        self.menuPurcahses.setObjectName("menuPurcahses")
        self.menuTransactions = QtWidgets.QMenu(self.menuMenu)
        self.menuTransactions.setObjectName("menuTransactions")
        self.menuReports = QtWidgets.QMenu(self.menuMenu)
        self.menuReports.setObjectName("menuReports")
        self.menuAdd = QtWidgets.QMenu(self.menuMenu)
        self.menuAdd.setObjectName("menuAdd")
        self.menuView = QtWidgets.QMenu(self.menuMenu)
        self.menuView.setObjectName("menuView")
        self.menuSales_2 = QtWidgets.QMenu(self.menubar)
        self.menuSales_2.setObjectName("menuSales_2")
        self.menuPurchases = QtWidgets.QMenu(self.menubar)
        self.menuPurchases.setObjectName("menuPurchases")
        self.menuItems = QtWidgets.QMenu(self.menubar)
        self.menuItems.setObjectName("menuItems")
        CentralWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(CentralWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        CentralWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionTools = QtWidgets.QAction(CentralWindow)
        self.actionTools.setObjectName("actionTools")
        self.actionHelp = QtWidgets.QAction(CentralWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionBack_Up_Data = QtWidgets.QAction(CentralWindow)
        self.actionBack_Up_Data.setObjectName("actionBack_Up_Data")
        self.actionRestore_Data = QtWidgets.QAction(CentralWindow)
        self.actionRestore_Data.setObjectName("actionRestore_Data")
        self.actionNew_Invoice = QtWidgets.QAction(CentralWindow)
        self.actionNew_Invoice.setObjectName("actionNew_Invoice")
        self.actionNew_Invoice.triggered.connect(lambda:self.newInvoiceFunc())
        self.actionApply_Customer_Payment = QtWidgets.QAction(CentralWindow)
        self.actionApply_Customer_Payment.setObjectName("actionApply_Customer_Payment")
        self.actionApply_Customer_Payment.triggered.connect(lambda:self.payFunc())
        self.actionOpen_Invoices_List = QtWidgets.QAction(CentralWindow)
        self.actionOpen_Invoices_List.setObjectName("actionOpen_Invoices_List")
        self.actionOpen_Invoices_List.triggered.connect(lambda:self.invoicesListFunc())
        self.actionReturn_Credit_Note = QtWidgets.QAction(CentralWindow)
        self.actionReturn_Credit_Note.setObjectName("actionReturn_Credit_Note")
        self.actionReturn_Credit_Note.triggered.connect(lambda:self.returnWindowFunc())
        self.action_New_Purchase_Order = QtWidgets.QAction(CentralWindow)
        self.action_New_Purchase_Order.setObjectName("action_New_Purchase_Order")
        self.action_New_Purchase_Order.triggered.connect(lambda:self.newPurchaseOrderFunc())
        self.actionOpen_Purchase_Order_List = QtWidgets.QAction(CentralWindow)
        self.actionOpen_Purchase_Order_List.setObjectName("actionOpen_Purchase_Order_List")
        self.actionOpen_Purchase_Order_List.triggered.connect(lambda:self.allPurchaseOrderViewFunc())
        self.actionMake_A_transaction = QtWidgets.QAction(CentralWindow)
        self.actionMake_A_transaction.setObjectName("actionMake_A_transaction")
        self.actionMake_A_transaction.triggered.connect(lambda:self.newTransFunc())
        self.actionTransaction_List = QtWidgets.QAction(CentralWindow)
        self.actionTransaction_List.setObjectName("actionTransaction_List")
        self.actionTransaction_List.triggered.connect(lambda:self.viewAllPaymentOfPurchaseOrderFunc())
        self.actionInvoices = QtWidgets.QAction(CentralWindow)
        self.actionInvoices.setObjectName("actionInvoices")
        self.actionPayments = QtWidgets.QAction(CentralWindow)
        self.actionPayments.setObjectName("actionPayments")
        self.actionBalance_Sheet = QtWidgets.QAction(CentralWindow)
        self.actionBalance_Sheet.setObjectName("actionBalance_Sheet")
        self.actionIncome_Statement = QtWidgets.QAction(CentralWindow)
        self.actionIncome_Statement.setObjectName("actionIncome_Statement")
        self.actionOther_Reports = QtWidgets.QAction(CentralWindow)
        self.actionOther_Reports.setObjectName("actionOther_Reports")
        self.actionnewTest = QtWidgets.QAction(CentralWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Academic/Semester 6/New folder/testing/ui/6448-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionnewTest.setIcon(icon)
        self.actionnewTest.setObjectName("actionnewTest")
        self.actionProduct = QtWidgets.QAction(CentralWindow)
        self.actionProduct.setObjectName("actionProduct")
        self.actionProduct.triggered.connect(lambda:self.viewItemFunc())
        self.actionSaleperson = QtWidgets.QAction(CentralWindow)
        self.actionSaleperson.setObjectName("actionSaleperson")
        self.actionSaleperson.triggered.connect(lambda:self.viewAllSuppliersFunc())
        self.actionEmployee = QtWidgets.QAction(CentralWindow)
        self.actionEmployee.setObjectName("actionEmployee")
        self.actionEmployee.triggered.connect(lambda:self.viewEmployeeFunc())
        self.actionEmployees = QtWidgets.QAction(CentralWindow)
        self.actionEmployees.setObjectName("actionEmployees")
        self.actionItems = QtWidgets.QAction(CentralWindow)
        self.actionItems.setObjectName("actionItems")
        self.actionNewClients=QtWidgets.QAction(CentralWindow)
        self.actionNewClients.setObjectName("actionNewClients")
        self.actionNewClients.triggered.connect(lambda:self.viewClientsFunc())
        self.actionProfit = QtWidgets.QAction(CentralWindow)
        self.actionProfit.setObjectName("actionProfit")
        self.actionSales = QtWidgets.QAction(CentralWindow)
        self.actionSales.setObjectName("actionSales")
        self.actionClients = QtWidgets.QAction(CentralWindow)
        self.actionClients.setObjectName("actionClients")
        self.actionPending_Payments = QtWidgets.QAction(CentralWindow)
        self.actionPending_Payments.setObjectName("actionPending_Payments")
        self.actionAdd_Payable = QtWidgets.QAction(CentralWindow)
        self.actionAdd_Payable.setObjectName("actionAdd_Payable")
        self.actionAdd_Payable.triggered.connect(lambda:self.detailPaymentOfPurchaseOrderFunc())
        self.actionInvoice = QtWidgets.QAction(CentralWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons/plus-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInvoice.setIcon(icon1)
        self.actionInvoice.setObjectName("actionInvoice")
        self.actionInvoice.triggered.connect(lambda:self.newInvoiceFunc())
        self.actionnew_Receiot = QtWidgets.QAction(CentralWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons/receipt-stamp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionnew_Receiot.setIcon(icon2)
        self.actionnew_Receiot.setObjectName("actionnew_Receiot")
        self.actionnew_Receiot.triggered.connect(lambda:self.payFunc())
        self.actionjournal = QtWidgets.QAction(CentralWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons/receipt--plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionjournal.setIcon(icon3)
        self.actionjournal.setObjectName("actionjournal")
        self.actionUpload_To_Server = QtWidgets.QAction(CentralWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons/computer-cloud.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpload_To_Server.setIcon(icon4)
        self.actionUpload_To_Server.setObjectName("actionUpload_To_Server")
        self.actiondownloadFromServer = QtWidgets.QAction(CentralWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons/download-cloud.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiondownloadFromServer.setIcon(icon5)
        self.actiondownloadFromServer.setObjectName("actiondownloadFromServer")
        self.actionoptions = QtWidgets.QAction(CentralWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons/screwdriver.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionoptions.setIcon(icon6)
        self.actionoptions.setObjectName("actionoptions")
        self.actionAdd = QtWidgets.QAction(CentralWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionAdd.triggered.connect(lambda:self.addItemFunc())
        self.actionView = QtWidgets.QAction(CentralWindow)
        self.actionView.setObjectName("actionView")
        self.actionView.triggered.connect(lambda:self.viewItemFunc())
        self.actionNew_Purchase_Order = QtWidgets.QAction(CentralWindow)
        self.actionNew_Purchase_Order.setObjectName("actionNew_Purchase_Order")
        self.actionNew_Purchase_Order.triggered.connect(lambda:self.newPurchaseOrderFunc())
        self.actionPurchase_Order_Lists = QtWidgets.QAction(CentralWindow)
        self.actionPurchase_Order_Lists.setObjectName("actionPurchase_Order_Lists")
        self.actionPurchase_Order_Lists.triggered.connect(lambda:self.allPurchaseOrderViewFunc())
        self.actionNew_Invoice_2 = QtWidgets.QAction(CentralWindow)
        self.actionNew_Invoice_2.setObjectName("actionNew_Invoice_2")
        self.actionNew_Invoice_2.triggered.connect(lambda:self.newInvoiceFunc())
        self.actionAdd_Payment = QtWidgets.QAction(CentralWindow)
        self.actionAdd_Payment.setObjectName("actionAdd_Payment")
        self.actionAdd_Payment.triggered.connect(lambda:self.payFunc())
        self.actionOpen_Invoices_List_2 = QtWidgets.QAction(CentralWindow)
        self.actionOpen_Invoices_List_2.setObjectName("actionOpen_Invoices_List_2")
        self.actionOpen_Invoices_List_2.triggered.connect(lambda:self.invoicesListFunc())
        self.menuAccounts.addAction(self.actionBack_Up_Data)
        self.menuAccounts.addAction(self.actionRestore_Data)
        self.menuSales.addAction(self.actionNew_Invoice)
        self.menuSales.addAction(self.actionApply_Customer_Payment)
        self.menuSales.addAction(self.actionOpen_Invoices_List)
        self.menuSales.addAction(self.actionReturn_Credit_Note)
        self.menuPurcahses.addAction(self.action_New_Purchase_Order)
        self.menuPurcahses.addAction(self.actionOpen_Purchase_Order_List)
        self.menuTransactions.addAction(self.actionMake_A_transaction)
        self.menuTransactions.addAction(self.actionTransaction_List)
        self.menuTransactions.addSeparator()
        self.menuTransactions.addAction(self.actionAdd_Payable)
        self.menuReports.addAction(self.actionInvoices)
        self.menuReports.addAction(self.actionPayments)
        self.menuReports.addAction(self.actionBalance_Sheet)
        self.menuReports.addAction(self.actionIncome_Statement)
        self.menuReports.addAction(self.actionOther_Reports)
        self.menuAdd.addAction(self.actionProduct)
        self.menuAdd.addAction(self.actionSaleperson)
        self.menuAdd.addAction(self.actionEmployee)
        self.menuAdd.addAction(self.actionNewClients)
        self.menuView.addAction(self.actionEmployees)
        self.menuView.addAction(self.actionItems)
        self.menuView.addAction(self.actionClients)
        self.menuView.addAction(self.actionSales)
        self.menuView.addSeparator()
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionProfit)
        self.menuView.addAction(self.actionPending_Payments)
        self.menuMenu.addAction(self.menuAccounts.menuAction())
        self.menuMenu.addAction(self.menuSales.menuAction())
        self.menuMenu.addAction(self.menuPurcahses.menuAction())
        self.menuMenu.addAction(self.menuTransactions.menuAction())
        self.menuMenu.addAction(self.menuReports.menuAction())
        self.menuMenu.addAction(self.menuAdd.menuAction())
        self.menuMenu.addAction(self.menuView.menuAction())
        self.menuMenu.addAction(self.actionHelp)
        self.menuSales_2.addAction(self.actionNew_Invoice_2)
        self.menuSales_2.addAction(self.actionAdd_Payment)
        self.menuSales_2.addAction(self.actionOpen_Invoices_List_2)
        self.menuPurchases.addAction(self.actionNew_Purchase_Order)
        self.menuPurchases.addAction(self.actionPurchase_Order_Lists)
        self.menuItems.addAction(self.actionAdd)
        self.menuItems.addAction(self.actionView)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuSales_2.menuAction())
        self.menubar.addAction(self.menuPurchases.menuAction())
        self.menubar.addAction(self.menuItems.menuAction())
        self.toolBar.addAction(self.actionInvoice)
        self.toolBar.addAction(self.actionnew_Receiot)
        self.toolBar.addAction(self.actionjournal)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUpload_To_Server)
        self.toolBar.addAction(self.actiondownloadFromServer)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionoptions)

        self.retranslateUi(CentralWindow)
        QtCore.QMetaObject.connectSlotsByName(CentralWindow)

    def viewItemFunc(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_viewItemWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def viewClientsFunc(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_viewClients()
        self.ui.setupUi(self.window)
        self.window.show()
    def addItemFunc(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_newItem()
        self.ui.setupUi(self.window)
        self.window.show()
    def viewEmployeeFunc(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_viewEmployee()
        self.ui.setupUi(self.window)
        self.window.show()
    def newInvoiceFunc(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_newInvoiceWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def payFunc(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_paymentWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def invoicesListFunc(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_allInvoicesView()
        self.ui.setupUi(self.window)
        self.window.show()
    def newPurchaseOrderFunc(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_purchaseOrder()
        self.ui.setupUi(self.window)
        self.window.show()
    def allPurchaseOrderViewFunc(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_allPurchaseOrderView()
        self.ui.setupUi(self.window)
        self.window.show()
    def newTransFunc(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_payPurchaseOrder()
        self.ui.setupUi(self.window)
        self.window.show()
    def viewAllPaymentOfPurchaseOrderFunc(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_allPaymetsOfPurchaseOrders()
        self.ui.setupUi(self.window)
        self.window.show()
    def detailPaymentOfPurchaseOrderFunc(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=allOrder()
        self.ui.setupUi(self.window)
        self.window.show()
    def viewAllSuppliersFunc(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_viewSuppliers()
        self.ui.setupUi(self.window)
        self.window.show()
    def returnWindowFunc(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_returnWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def retranslateUi(self, CentralWindow):
        _translate = QtCore.QCoreApplication.translate
        CentralWindow.setWindowTitle(_translate("CentralWindow", "Accounting Software"))
        self.menuMenu.setTitle(_translate("CentralWindow", "Menu"))
        self.menuAccounts.setTitle(_translate("CentralWindow", "Accounts"))
        self.menuSales.setTitle(_translate("CentralWindow", "Sales"))
        self.menuPurcahses.setTitle(_translate("CentralWindow", "Purcahses"))
        self.menuTransactions.setTitle(_translate("CentralWindow", "Transactions"))
        self.menuReports.setTitle(_translate("CentralWindow", "Reports"))
        self.menuAdd.setTitle(_translate("CentralWindow", "Add"))
        self.menuView.setTitle(_translate("CentralWindow", "View"))
        self.menuSales_2.setTitle(_translate("CentralWindow", "Sales"))
        self.menuPurchases.setTitle(_translate("CentralWindow", "Purchases"))
        self.menuItems.setTitle(_translate("CentralWindow", "Items"))
        self.toolBar.setWindowTitle(_translate("CentralWindow", "toolBar"))
        self.actionTools.setText(_translate("CentralWindow", "Tools"))
        self.actionHelp.setText(_translate("CentralWindow", "Help"))
        self.actionBack_Up_Data.setText(_translate("CentralWindow", "Back Up Data..."))
        self.actionRestore_Data.setText(_translate("CentralWindow", "Restore Data..."))
        self.actionNew_Invoice.setText(_translate("CentralWindow", "New Invoice"))
        self.actionApply_Customer_Payment.setText(_translate("CentralWindow", "Apply Customer Payment"))
        self.actionOpen_Invoices_List.setText(_translate("CentralWindow", "Open Invoices List"))
        self.actionReturn_Credit_Note.setText(_translate("CentralWindow", "Return/Credit Note"))
        self.action_New_Purchase_Order.setText(_translate("CentralWindow", " New Purchase Order"))
        self.actionOpen_Purchase_Order_List.setText(_translate("CentralWindow", "Open Purchase Order List"))
        self.actionMake_A_transaction.setText(_translate("CentralWindow", "New Transaction"))
        self.actionTransaction_List.setText(_translate("CentralWindow", "Transaction List"))
        self.actionInvoices.setText(_translate("CentralWindow", "Invoices"))
        self.actionPayments.setText(_translate("CentralWindow", "Payments"))
        self.actionBalance_Sheet.setText(_translate("CentralWindow", "Balance Sheet"))
        self.actionIncome_Statement.setText(_translate("CentralWindow", "Income Statement "))
        self.actionOther_Reports.setText(_translate("CentralWindow", "Other Reports"))
        self.actionnewTest.setText(_translate("CentralWindow", "newTest"))
        self.actionnewTest.setToolTip(_translate("CentralWindow", "forTesting"))
        self.actionProduct.setText(_translate("CentralWindow", "Item"))
        self.actionSaleperson.setText(_translate("CentralWindow", "Supplier"))
        self.actionEmployee.setText(_translate("CentralWindow", "Employee"))
        self.actionNewClients.setText(_translate("CentralWindow", "Client"))
        self.actionEmployees.setText(_translate("CentralWindow", "Employees"))
        self.actionItems.setText(_translate("CentralWindow", "Items"))
        self.actionProfit.setText(_translate("CentralWindow", "Profit"))
        self.actionSales.setText(_translate("CentralWindow", "Sales"))
        self.actionClients.setText(_translate("CentralWindow", "Clients"))
        self.actionPending_Payments.setText(_translate("CentralWindow", "Pending Payments"))
        self.actionAdd_Payable.setText(_translate("CentralWindow", "View Payments Details"))
        self.actionInvoice.setText(_translate("CentralWindow", "Invoice"))
        self.actionInvoice.setToolTip(_translate("CentralWindow", "New Invoice"))
        self.actionnew_Receiot.setText(_translate("CentralWindow", "Payment"))
        self.actionnew_Receiot.setToolTip(_translate("CentralWindow", "Apply a Payment Received"))
        self.actionjournal.setText(_translate("CentralWindow", "Journal"))
        self.actionjournal.setToolTip(_translate("CentralWindow", "Add a Journal Voucher"))
        self.actionUpload_To_Server.setText(_translate("CentralWindow", "Upload To Server"))
        self.actionUpload_To_Server.setToolTip(_translate("CentralWindow", "Upload To Server"))
        self.actiondownloadFromServer.setText(_translate("CentralWindow", "Download From Server"))
        self.actiondownloadFromServer.setToolTip(_translate("CentralWindow", "Download From Server"))
        self.actionoptions.setText(_translate("CentralWindow", "Options"))
        self.actionoptions.setToolTip(_translate("CentralWindow", "Options"))
        self.actionAdd.setText(_translate("CentralWindow", "Add"))
        self.actionView.setText(_translate("CentralWindow", "View"))
        self.actionNew_Purchase_Order.setText(_translate("CentralWindow", "New Purchase Order"))
        self.actionPurchase_Order_Lists.setText(_translate("CentralWindow", "Purchase Order Lists"))
        self.actionNew_Invoice_2.setText(_translate("CentralWindow", "New Invoice"))
        self.actionAdd_Payment.setText(_translate("CentralWindow", "Add Payment"))
        self.actionOpen_Invoices_List_2.setText(_translate("CentralWindow", "Open  Invoices List"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CentralWindow = QtWidgets.QMainWindow()
    ui = Ui_CentralWindow()
    ui.setupUi(CentralWindow)
    CentralWindow.show()
    sys.exit(app.exec_())
