# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PayPurchaseOrder.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_payPurchaseOrder(object):
    def setupUi(self, payPurchaseOrder):
        payPurchaseOrder.setObjectName("payPurchaseOrder")
        payPurchaseOrder.resize(677, 491)
        self.centralwidget = QtWidgets.QWidget(payPurchaseOrder)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 40, 641, 151))
        self.frame.setStyleSheet("border:1px solid rgb(215, 215, 215);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.label_3.setStyleSheet("border:0px;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.label_4.setStyleSheet("border:0px;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.label_5.setStyleSheet("border:0px;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 61, 21))
        self.label_6.setStyleSheet("border:0px;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(410, 80, 61, 21))
        self.label_7.setObjectName("label_7")
        self.dateEdit = QtWidgets.QDateEdit(self.frame)
        self.dateEdit.setGeometry(QtCore.QRect(159, 20, 461, 22))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.supplierCombo = QtWidgets.QComboBox(self.frame)
        self.supplierCombo.setGeometry(QtCore.QRect(160, 50, 381, 22))
        self.supplierCombo.setObjectName("supplierCombo")
        self.supplierCombo.addItem("")
        self.supplierCombo.addItem("")
        self.methodCombo = QtWidgets.QComboBox(self.frame)
        self.methodCombo.setGeometry(QtCore.QRect(160, 80, 231, 22))
        self.methodCombo.setObjectName("methodCombo")
        self.methodCombo.addItem("")
        self.methodCombo.addItem("")
        self.methodCombo.addItem("")
        self.amountInput = QtWidgets.QLineEdit(self.frame)
        self.amountInput.setGeometry(QtCore.QRect(160, 110, 461, 20))
        self.amountInput.setText("")
        self.amountInput.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.amountInput.setObjectName("amountInput")
        self.checkInput = QtWidgets.QLineEdit(self.frame)
        self.checkInput.setEnabled(False)
        self.checkInput.setGeometry(QtCore.QRect(480, 80, 141, 20))
        self.checkInput.setObjectName("checkInput")
        self.allCustomersTool = QtWidgets.QToolButton(self.frame)
        self.allCustomersTool.setGeometry(QtCore.QRect(550, 50, 25, 19))
        self.allCustomersTool.setStyleSheet("border:0px;")
        self.allCustomersTool.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons8-customer-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.allCustomersTool.setIcon(icon)
        self.allCustomersTool.setAutoRaise(False)
        self.allCustomersTool.setObjectName("allCustomersTool")
        self.editCustomerToolBtn = QtWidgets.QToolButton(self.frame)
        self.editCustomerToolBtn.setGeometry(QtCore.QRect(590, 50, 25, 19))
        self.editCustomerToolBtn.setStyleSheet("border:0px;")
        self.editCustomerToolBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editCustomerToolBtn.setIcon(icon1)
        self.editCustomerToolBtn.setObjectName("editCustomerToolBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 51, 16))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 220, 641, 221))
        self.frame_2.setStyleSheet("border:1px solid rgb(215, 215, 215);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 151, 16))
        self.label_8.setStyleSheet("border:0px;")
        self.label_8.setObjectName("label_8")
        self.unappliedAmountRemainingInput = QtWidgets.QLabel(self.frame_2)
        self.unappliedAmountRemainingInput.setGeometry(QtCore.QRect(466, 10, 111, 16))
        self.unappliedAmountRemainingInput.setStyleSheet("border:0px;")
        self.unappliedAmountRemainingInput.setObjectName("unappliedAmountRemainingInput")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 611, 181))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 200, 51, 20))
        self.label_2.setObjectName("label_2")
        self.recordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.recordBtn.setGeometry(QtCore.QRect(420, 450, 75, 23))
        self.recordBtn.setObjectName("recordBtn")
        self.cancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBtn.setGeometry(QtCore.QRect(500, 450, 75, 23))
        self.cancelBtn.setObjectName("cancelBtn")
        self.helpBtn = QtWidgets.QPushButton(self.centralwidget)
        self.helpBtn.setGeometry(QtCore.QRect(580, 450, 75, 23))
        self.helpBtn.setObjectName("helpBtn")
        payPurchaseOrder.setCentralWidget(self.centralwidget)

        self.retranslateUi(payPurchaseOrder)
        QtCore.QMetaObject.connectSlotsByName(payPurchaseOrder)

    def retranslateUi(self, payPurchaseOrder):
        _translate = QtCore.QCoreApplication.translate
        payPurchaseOrder.setWindowTitle(_translate("payPurchaseOrder", "Payment"))
        self.label_3.setText(_translate("payPurchaseOrder", "Date:"))
        self.label_4.setText(_translate("payPurchaseOrder", "Supplier:"))
        self.label_5.setText(_translate("payPurchaseOrder", "Method:"))
        self.label_6.setText(_translate("payPurchaseOrder", "Amount:"))
        self.label_7.setText(_translate("payPurchaseOrder", "Check no:"))
        self.supplierCombo.setItemText(0, _translate("payPurchaseOrder", "Ashfaq Chemicals"))
        self.supplierCombo.setItemText(1, _translate("payPurchaseOrder", "Highlight Seeds"))
        self.methodCombo.setItemText(0, _translate("payPurchaseOrder", "Cash"))
        self.methodCombo.setItemText(1, _translate("payPurchaseOrder", "Check"))
        self.methodCombo.setItemText(2, _translate("payPurchaseOrder", "Bank Transfer"))
        self.checkInput.setText(_translate("payPurchaseOrder", "1"))
        self.label.setText(_translate("payPurchaseOrder", "Payment:"))
        self.label_8.setText(_translate("payPurchaseOrder", "Unapplied amount remaining:"))
        self.unappliedAmountRemainingInput.setText(_translate("payPurchaseOrder", "Rs 0.00"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("payPurchaseOrder", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("payPurchaseOrder", "2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("payPurchaseOrder", "Bill #"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("payPurchaseOrder", "Date"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("payPurchaseOrder", "Date due"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("payPurchaseOrder", "Total"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("payPurchaseOrder", "Amount Due"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("payPurchaseOrder", "Applied"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("payPurchaseOrder", "1231"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("payPurchaseOrder", "2021-12-12"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("payPurchaseOrder", "1234"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("payPurchaseOrder", "2021-11-11"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("payPurchaseOrder", "Bill:"))
        self.recordBtn.setText(_translate("payPurchaseOrder", "Record"))
        self.cancelBtn.setText(_translate("payPurchaseOrder", "Cancel"))
        self.helpBtn.setText(_translate("payPurchaseOrder", "Help"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    payPurchaseOrder = QtWidgets.QMainWindow()
    ui = Ui_payPurchaseOrder()
    ui.setupUi(payPurchaseOrder)
    payPurchaseOrder.show()
    sys.exit(app.exec_())
