# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'purchaseOrder.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_purchaseOrder(object):
    def setupUi(self, purchaseOrder):
        purchaseOrder.setObjectName("purchaseOrder")
        purchaseOrder.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(purchaseOrder)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 13, 81, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 20, 47, 16))
        self.label_2.setObjectName("label_2")
        self.supplierComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.supplierComboBox.setGeometry(QtCore.QRect(10, 40, 231, 22))
        self.supplierComboBox.setObjectName("supplierComboBox")
        self.supplierComboBox.addItem("")
        self.allVendorsToolBtn = QtWidgets.QToolButton(self.centralwidget)
        self.allVendorsToolBtn.setGeometry(QtCore.QRect(250, 40, 25, 19))
        self.allVendorsToolBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons8-customer-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.allVendorsToolBtn.setIcon(icon)
        self.allVendorsToolBtn.setAutoRaise(True)
        self.allVendorsToolBtn.setObjectName("allVendorsToolBtn")
        self.EditVendorToolBtn = QtWidgets.QToolButton(self.centralwidget)
        self.EditVendorToolBtn.setGeometry(QtCore.QRect(280, 40, 25, 19))
        self.EditVendorToolBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EditVendorToolBtn.setIcon(icon1)
        self.EditVendorToolBtn.setAutoRaise(True)
        self.EditVendorToolBtn.setObjectName("EditVendorToolBtn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.label_3.setObjectName("label_3")
        self.vendorAddressEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.vendorAddressEdit.setGeometry(QtCore.QRect(10, 100, 301, 71))
        self.vendorAddressEdit.setObjectName("vendorAddressEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(440, 70, 47, 16))
        self.label_4.setObjectName("label_4")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(630, 20, 141, 21))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.shipToEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.shipToEdit.setGeometry(QtCore.QRect(440, 100, 331, 71))
        self.shipToEdit.setObjectName("shipToEdit")
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(10, 400, 75, 23))
        self.addBtn.setObjectName("addBtn")
        self.removeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.removeBtn.setGeometry(QtCore.QRect(100, 400, 75, 23))
        self.removeBtn.setObjectName("removeBtn")
        self.discountBtn = QtWidgets.QPushButton(self.centralwidget)
        self.discountBtn.setGeometry(QtCore.QRect(190, 400, 75, 23))
        self.discountBtn.setObjectName("discountBtn")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 440, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(230, 440, 101, 16))
        self.label_6.setObjectName("label_6")
        self.commentsTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.commentsTextEdit.setGeometry(QtCore.QRect(10, 460, 201, 71))
        self.commentsTextEdit.setObjectName("commentsTextEdit")
        self.privateCommentTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.privateCommentTextEdit.setGeometry(QtCore.QRect(230, 460, 201, 71))
        self.privateCommentTextEdit.setObjectName("privateCommentTextEdit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(510, 450, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(510, 470, 47, 13))
        self.label_8.setObjectName("label_8")
        self.subtotalShowLabel = QtWidgets.QLabel(self.centralwidget)
        self.subtotalShowLabel.setGeometry(QtCore.QRect(680, 450, 47, 13))
        self.subtotalShowLabel.setObjectName("subtotalShowLabel")
        self.totalShowLabel = QtWidgets.QLabel(self.centralwidget)
        self.totalShowLabel.setGeometry(QtCore.QRect(680, 470, 47, 13))
        self.totalShowLabel.setObjectName("totalShowLabel")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 180, 761, 211))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 5, item)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 540, 771, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.saveAndPreviewBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveAndPreviewBtn.setGeometry(QtCore.QRect(10, 560, 101, 23))
        self.saveAndPreviewBtn.setObjectName("saveAndPreviewBtn")
        self.recordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.recordBtn.setGeometry(QtCore.QRect(440, 560, 101, 23))
        self.recordBtn.setObjectName("recordBtn")
        self.cancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBtn.setGeometry(QtCore.QRect(560, 560, 101, 23))
        self.cancelBtn.setObjectName("cancelBtn")
        self.helpBtn = QtWidgets.QPushButton(self.centralwidget)
        self.helpBtn.setGeometry(QtCore.QRect(680, 560, 101, 23))
        self.helpBtn.setObjectName("helpBtn")
        purchaseOrder.setCentralWidget(self.centralwidget)

        self.retranslateUi(purchaseOrder)
        QtCore.QMetaObject.connectSlotsByName(purchaseOrder)

    def retranslateUi(self, purchaseOrder):
        _translate = QtCore.QCoreApplication.translate
        purchaseOrder.setWindowTitle(_translate("purchaseOrder", "New Purchase Order"))
        self.label.setText(_translate("purchaseOrder", "Order Supplier:"))
        self.label_2.setText(_translate("purchaseOrder", "Date:"))
        self.supplierComboBox.setItemText(0, _translate("purchaseOrder", "Ashfaq Chemicals"))
        self.label_3.setText(_translate("purchaseOrder", "Vendor Address:"))
        self.vendorAddressEdit.setPlaceholderText(_translate("purchaseOrder", "[Enter Vendor Address]"))
        self.label_4.setText(_translate("purchaseOrder", "Ship To:"))
        self.shipToEdit.setHtml(_translate("purchaseOrder", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">888 E joharTown Lahore</p></body></html>"))
        self.addBtn.setText(_translate("purchaseOrder", "Add Item"))
        self.removeBtn.setText(_translate("purchaseOrder", "Remove Item"))
        self.discountBtn.setText(_translate("purchaseOrder", "Add Discount"))
        self.label_5.setText(_translate("purchaseOrder", "Comments:"))
        self.label_6.setText(_translate("purchaseOrder", "Private Comments:"))
        self.commentsTextEdit.setToolTip(_translate("purchaseOrder", "Comments Printed On Receipt"))
        self.commentsTextEdit.setPlaceholderText(_translate("purchaseOrder", "[Enter Comments Here]"))
        self.privateCommentTextEdit.setToolTip(_translate("purchaseOrder", "Private Comments Not Shown On Receipt"))
        self.privateCommentTextEdit.setPlaceholderText(_translate("purchaseOrder", "[Enter Private Comments Here]"))
        self.label_7.setText(_translate("purchaseOrder", "Subtotal:"))
        self.label_8.setText(_translate("purchaseOrder", "<html><head/><body><p><span style=\" font-weight:600;\">Total:</span></p></body></html>"))
        self.subtotalShowLabel.setText(_translate("purchaseOrder", "RS 0"))
        self.totalShowLabel.setText(_translate("purchaseOrder", "<html><head/><body><p><span style=\" font-weight:600;\">RS 0</span></p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("purchaseOrder", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("purchaseOrder", "2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("purchaseOrder", "Qty"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("purchaseOrder", "Item"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("purchaseOrder", "Description"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("purchaseOrder", "Unit Price"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("purchaseOrder", "Discount"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("purchaseOrder", "Total"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("purchaseOrder", "1"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("purchaseOrder", "astrazanica"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("purchaseOrder", "dada"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("purchaseOrder", "200"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("purchaseOrder", "200"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("purchaseOrder", "5"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("purchaseOrder", "unho"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("purchaseOrder", "adad"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("purchaseOrder", "100"))
        item = self.tableWidget.item(1, 5)
        item.setText(_translate("purchaseOrder", "500"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.saveAndPreviewBtn.setText(_translate("purchaseOrder", "Save and Preview"))
        self.recordBtn.setText(_translate("purchaseOrder", "Record"))
        self.cancelBtn.setText(_translate("purchaseOrder", "Cancel"))
        self.helpBtn.setText(_translate("purchaseOrder", "Help"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    purchaseOrder = QtWidgets.QMainWindow()
    ui = Ui_purchaseOrder()
    ui.setupUi(purchaseOrder)
    purchaseOrder.show()
    sys.exit(app.exec_())
