# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'returnWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_returnWindow(object):
    def setupUi(self, returnWindow):
        returnWindow.setObjectName("returnWindow")
        returnWindow.setEnabled(True)
        returnWindow.resize(786, 594)
        returnWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(returnWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 30, 431, 181))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 31, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 31, 22))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 140, 42, 22))
        self.label_8.setObjectName("label_8")
        self.nameInput = QtWidgets.QLineEdit(self.frame)
        self.nameInput.setGeometry(QtCore.QRect(80, 10, 251, 20))
        self.nameInput.setObjectName("nameInput")
        self.billToInput = QtWidgets.QTextEdit(self.frame)
        self.billToInput.setGeometry(QtCore.QRect(80, 40, 331, 71))
        self.billToInput.setObjectName("billToInput")
        self.contactInput = QtWidgets.QLineEdit(self.frame)
        self.contactInput.setGeometry(QtCore.QRect(80, 140, 331, 20))
        self.contactInput.setObjectName("contactInput")
        self.showAllToolBtn = QtWidgets.QToolButton(self.frame)
        self.showAllToolBtn.setGeometry(QtCore.QRect(340, 10, 26, 25))
        self.showAllToolBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons8-customer-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showAllToolBtn.setIcon(icon)
        self.showAllToolBtn.setAutoRaise(True)
        self.showAllToolBtn.setObjectName("showAllToolBtn")
        self.editToolBtn = QtWidgets.QToolButton(self.frame)
        self.editToolBtn.setEnabled(False)
        self.editToolBtn.setGeometry(QtCore.QRect(380, 11, 25, 20))
        self.editToolBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editToolBtn.setIcon(icon1)
        self.editToolBtn.setAutoRaise(True)
        self.editToolBtn.setObjectName("editToolBtn")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(470, 30, 291, 181))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 40, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(10, 130, 81, 16))
        self.label_13.setObjectName("label_13")
        self.createFromInvoiceComboBOx = QtWidgets.QComboBox(self.frame_2)
        self.createFromInvoiceComboBOx.setGeometry(QtCore.QRect(100, 10, 141, 20))
        self.createFromInvoiceComboBOx.setObjectName("createFromInvoiceComboBOx")
        self.createFromInvoiceComboBOx.addItem("")
        self.createFromInvoiceComboBOx.addItem("")
        self.dateEdit = QtWidgets.QDateEdit(self.frame_2)
        self.dateEdit.setGeometry(QtCore.QRect(100, 40, 171, 22))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(False)
        self.dateEdit.setObjectName("dateEdit")
        self.invoiceNumberInput = QtWidgets.QLineEdit(self.frame_2)
        self.invoiceNumberInput.setEnabled(False)
        self.invoiceNumberInput.setGeometry(QtCore.QRect(100, 130, 171, 20))
        self.invoiceNumberInput.setObjectName("invoiceNumberInput")
        self.invoiceToolBtn = QtWidgets.QToolButton(self.frame_2)
        self.invoiceToolBtn.setGeometry(QtCore.QRect(250, 10, 25, 19))
        self.invoiceToolBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons/receipt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.invoiceToolBtn.setIcon(icon2)
        self.invoiceToolBtn.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.invoiceToolBtn.setAutoRaise(True)
        self.invoiceToolBtn.setObjectName("invoiceToolBtn")
        self.salepersonInputAuto = QtWidgets.QLineEdit(self.frame_2)
        self.salepersonInputAuto.setEnabled(False)
        self.salepersonInputAuto.setGeometry(QtCore.QRect(100, 100, 171, 20))
        self.salepersonInputAuto.setObjectName("salepersonInputAuto")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.label_11.setObjectName("label_11")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.frame_2)
        self.dateEdit_2.setEnabled(False)
        self.dateEdit_2.setGeometry(QtCore.QRect(100, 70, 171, 22))
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setCalendarPopup(False)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(20, 240, 741, 181))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 741, 181))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons/bin-metal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget.setItem(1, 6, item)
        self.toolButton = QtWidgets.QToolButton(self.frame_3)
        self.toolButton.setGeometry(QtCore.QRect(620, 60, 25, 19))
        self.toolButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons/bin-metal-full.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon4)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.addItemBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addItemBtn.setEnabled(False)
        self.addItemBtn.setGeometry(QtCore.QRect(40, 430, 91, 23))
        self.addItemBtn.setObjectName("addItemBtn")
        self.removeItemBtn = QtWidgets.QPushButton(self.centralwidget)
        self.removeItemBtn.setEnabled(False)
        self.removeItemBtn.setGeometry(QtCore.QRect(140, 430, 91, 23))
        self.removeItemBtn.setObjectName("removeItemBtn")
        self.subTotalLabel = QtWidgets.QLabel(self.centralwidget)
        self.subTotalLabel.setGeometry(QtCore.QRect(480, 450, 47, 13))
        self.subTotalLabel.setObjectName("subTotalLabel")
        self.totalLabel = QtWidgets.QLabel(self.centralwidget)
        self.totalLabel.setGeometry(QtCore.QRect(480, 470, 41, 20))
        self.totalLabel.setObjectName("totalLabel")
        self.subtotalShowLabel = QtWidgets.QLabel(self.centralwidget)
        self.subtotalShowLabel.setGeometry(QtCore.QRect(680, 450, 101, 16))
        self.subtotalShowLabel.setObjectName("subtotalShowLabel")
        self.totalShowLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.totalShowLabel_2.setGeometry(QtCore.QRect(670, 470, 101, 16))
        self.totalShowLabel_2.setObjectName("totalShowLabel_2")
        self.commentsEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.commentsEdit.setGeometry(QtCore.QRect(20, 490, 191, 41))
        self.commentsEdit.setObjectName("commentsEdit")
        self.privateCommentsEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.privateCommentsEdit.setGeometry(QtCore.QRect(230, 490, 191, 41))
        self.privateCommentsEdit.setObjectName("privateCommentsEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 470, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 470, 101, 16))
        self.label_2.setObjectName("label_2")
        self.addDiscountBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addDiscountBtn.setEnabled(False)
        self.addDiscountBtn.setGeometry(QtCore.QRect(240, 430, 91, 23))
        self.addDiscountBtn.setObjectName("addDiscountBtn")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 540, 741, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 10, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 220, 47, 13))
        self.label_5.setObjectName("label_5")
        self.recordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.recordBtn.setGeometry(QtCore.QRect(510, 560, 75, 23))
        self.recordBtn.setObjectName("recordBtn")
        self.cancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBtn.setGeometry(QtCore.QRect(600, 560, 75, 23))
        self.cancelBtn.setObjectName("cancelBtn")
        self.helpBtn = QtWidgets.QPushButton(self.centralwidget)
        self.helpBtn.setGeometry(QtCore.QRect(690, 560, 75, 23))
        self.helpBtn.setObjectName("helpBtn")
        returnWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(returnWindow)
        QtCore.QMetaObject.connectSlotsByName(returnWindow)

    def retranslateUi(self, returnWindow):
        _translate = QtCore.QCoreApplication.translate
        returnWindow.setWindowTitle(_translate("returnWindow", "Return a Sale"))
        self.label_6.setText(_translate("returnWindow", "Name:"))
        self.label_7.setText(_translate("returnWindow", "Bill To:"))
        self.label_8.setText(_translate("returnWindow", "Contact:"))
        self.showAllToolBtn.setToolTip(_translate("returnWindow", "Open Customer Record"))
        self.editToolBtn.setToolTip(_translate("returnWindow", "Edit Customer Record"))
        self.label_9.setText(_translate("returnWindow", "Create From:"))
        self.label_10.setText(_translate("returnWindow", "Date:"))
        self.label_12.setText(_translate("returnWindow", "Saleperson:"))
        self.label_13.setText(_translate("returnWindow", "Invoice Number:"))
        self.createFromInvoiceComboBOx.setItemText(0, _translate("returnWindow", "Invoice..."))
        self.createFromInvoiceComboBOx.setItemText(1, _translate("returnWindow", "[Custom]"))
        self.invoiceToolBtn.setToolTip(_translate("returnWindow", "Old Invoices"))
        self.label_11.setText(_translate("returnWindow", "Invoice Date:"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("returnWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("returnWindow", "2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("returnWindow", "Qty"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("returnWindow", "Item"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("returnWindow", "Description"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("returnWindow", "Unit Price"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("returnWindow", "Discount"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("returnWindow", "Total"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("returnWindow", "12"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("returnWindow", "astrazanica"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("returnWindow", "covid vacine"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("returnWindow", "500"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("returnWindow", "0%"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("returnWindow", "6000"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("returnWindow", "4"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("returnWindow", "herba"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("returnWindow", "herbicide"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("returnWindow", "1000"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("returnWindow", "0%"))
        item = self.tableWidget.item(1, 5)
        item.setText(_translate("returnWindow", "4000"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.addItemBtn.setText(_translate("returnWindow", "Add Item"))
        self.removeItemBtn.setText(_translate("returnWindow", "Remove Item"))
        self.subTotalLabel.setText(_translate("returnWindow", "Subtotal:"))
        self.totalLabel.setText(_translate("returnWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Total:</span></p></body></html>"))
        self.subtotalShowLabel.setText(_translate("returnWindow", "RS 10,000"))
        self.totalShowLabel_2.setText(_translate("returnWindow", "<html><head/><body><p><span style=\" font-weight:600;\">RS 10,000</span></p></body></html>"))
        self.commentsEdit.setToolTip(_translate("returnWindow", "These notes are printed on the bottom of the invoice"))
        self.commentsEdit.setPlaceholderText(_translate("returnWindow", "[Enter Invoice Notes]"))
        self.privateCommentsEdit.setToolTip(_translate("returnWindow", "These are internal notes not printed on the invoice"))
        self.privateCommentsEdit.setPlaceholderText(_translate("returnWindow", "[Enter internal Notes]"))
        self.label.setText(_translate("returnWindow", "Comments"))
        self.label_2.setText(_translate("returnWindow", "Private Comments"))
        self.addDiscountBtn.setText(_translate("returnWindow", "Add Discount..."))
        self.label_3.setText(_translate("returnWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Customer</span></p></body></html>"))
        self.label_4.setText(_translate("returnWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Invoice</span></p><p><br/></p></body></html>"))
        self.label_5.setText(_translate("returnWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Sale</span></p></body></html>"))
        self.recordBtn.setText(_translate("returnWindow", "Record"))
        self.cancelBtn.setText(_translate("returnWindow", "Cancel"))
        self.helpBtn.setText(_translate("returnWindow", "Help"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    returnWindow = QtWidgets.QMainWindow()
    ui = Ui_returnWindow()
    ui.setupUi(returnWindow)
    returnWindow.show()
    sys.exit(app.exec_())
