# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewEmployee.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from newEmployee import Ui_newEmployee


class Ui_viewEmployee(object):
    def setupUi(self, viewEmployee):
        viewEmployee.setObjectName("viewEmployee")
        viewEmployee.resize(797, 600)
        self.centralwidget = QtWidgets.QWidget(viewEmployee)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 41))
        self.frame.setStyleSheet("background-color: rgb(209, 202, 214);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(70, 10, 113, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(200, 10, 75, 23))
        self.pushButton.setStyleSheet("background-color: rgb(165, 159, 159);")
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(0, 40, 801, 511))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        viewEmployee.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(viewEmployee)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 797, 21))
        self.menubar.setObjectName("menubar")
        self.menuItem = QtWidgets.QMenu(self.menubar)
        self.menuItem.setObjectName("menuItem")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        viewEmployee.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(viewEmployee)
        self.toolBar.setObjectName("toolBar")
        viewEmployee.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAdd = QtWidgets.QAction(viewEmployee)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons/plus-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd.setIcon(icon)
        self.actionAdd.setObjectName("actionAdd")
        self.actionAdd.triggered.connect(lambda:self.addNewFunc())
        self.actionDelete = QtWidgets.QAction(viewEmployee)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons/cross-octagon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon1)
        self.actionDelete.setObjectName("actionDelete")
        self.actionEdit = QtWidgets.QAction(viewEmployee)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit.setIcon(icon2)
        self.actionEdit.setObjectName("actionEdit")
        self.actionPrint = QtWidgets.QAction(viewEmployee)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/MOIZ/Downloads/icons/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon3)
        self.actionPrint.setObjectName("actionPrint")
        self.actionAdd_new_Employee = QtWidgets.QAction(viewEmployee)
        self.actionAdd_new_Employee.setObjectName("actionAdd_new_Employee")
        self.actionDelete_this_Item = QtWidgets.QAction(viewEmployee)
        self.actionDelete_this_Item.setObjectName("actionDelete_this_Item")
        self.actionEdit_this_Item = QtWidgets.QAction(viewEmployee)
        self.actionEdit_this_Item.setObjectName("actionEdit_this_Item")
        self.actionFind_Item = QtWidgets.QAction(viewEmployee)
        self.actionFind_Item.setObjectName("actionFind_Item")
        self.actionFind_Next_Item = QtWidgets.QAction(viewEmployee)
        self.actionFind_Next_Item.setObjectName("actionFind_Next_Item")
        self.actionReport = QtWidgets.QAction(viewEmployee)
        self.actionReport.setObjectName("actionReport")
        self.actionImport_Items_From_CSV = QtWidgets.QAction(viewEmployee)
        self.actionImport_Items_From_CSV.setObjectName("actionImport_Items_From_CSV")
        self.actionClose = QtWidgets.QAction(viewEmployee)
        self.actionClose.setObjectName("actionClose")
        self.actionHelp_Contents = QtWidgets.QAction(viewEmployee)
        self.actionHelp_Contents.setObjectName("actionHelp_Contents")
        self.actionContact_Software_Developer = QtWidgets.QAction(viewEmployee)
        self.actionContact_Software_Developer.setObjectName("actionContact_Software_Developer")
        self.menuItem.addAction(self.actionAdd_new_Employee)
        self.menuItem.addAction(self.actionDelete_this_Item)
        self.menuItem.addAction(self.actionEdit_this_Item)
        self.menuItem.addSeparator()
        self.menuItem.addAction(self.actionFind_Item)
        self.menuItem.addAction(self.actionFind_Next_Item)
        self.menuItem.addSeparator()
        self.menuItem.addAction(self.actionReport)
        self.menuItem.addSeparator()
        self.menuItem.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionHelp_Contents)
        self.menuHelp.addAction(self.actionContact_Software_Developer)
        self.menubar.addAction(self.menuItem.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addAction(self.actionEdit)
        self.toolBar.addAction(self.actionPrint)

        self.retranslateUi(viewEmployee)
        QtCore.QMetaObject.connectSlotsByName(viewEmployee)

    def addNewFunc(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_newEmployee()
        self.ui.setupUi(self.window)
        self.window.show()
    def retranslateUi(self, viewEmployee):
        _translate = QtCore.QCoreApplication.translate
        viewEmployee.setWindowTitle(_translate("viewEmployee", "Employees"))
        self.label.setText(_translate("viewEmployee", "Find Item:"))
        self.pushButton.setText(_translate("viewEmployee", "Find"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("viewEmployee", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("viewEmployee", "2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("viewEmployee", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("viewEmployee", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("viewEmployee", "Address"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("viewEmployee", "Salary"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("viewEmployee", "Job Description"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("viewEmployee", "1"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("viewEmployee", "ali"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("viewEmployee", "arif"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("viewEmployee", "18000"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("viewEmployee", "saleman"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("viewEmployee", "2"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("viewEmployee", "hamza"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("viewEmployee", "arif"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("viewEmployee", "18000"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("viewEmployee", "employee"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.menuItem.setTitle(_translate("viewEmployee", "Employee"))
        self.menuHelp.setTitle(_translate("viewEmployee", "Help"))
        self.toolBar.setWindowTitle(_translate("viewEmployee", "toolBar"))
        self.actionAdd.setText(_translate("viewEmployee", "Add"))
        self.actionAdd.setToolTip(_translate("viewEmployee", "Add a new Item"))
        self.actionDelete.setText(_translate("viewEmployee", "Delete"))
        self.actionDelete.setToolTip(_translate("viewEmployee", "Delete a Item"))
        self.actionEdit.setText(_translate("viewEmployee", "Edit"))
        self.actionEdit.setToolTip(_translate("viewEmployee", "Edit an Item"))
        self.actionPrint.setText(_translate("viewEmployee", "Print"))
        self.actionPrint.setToolTip(_translate("viewEmployee", "Print Report"))
        self.actionAdd_new_Employee.setText(_translate("viewEmployee", "Add new Employee"))
        self.actionDelete_this_Item.setText(_translate("viewEmployee", "Delete this Employee"))
        self.actionEdit_this_Item.setText(_translate("viewEmployee", "Edit this Employee"))
        self.actionFind_Item.setText(_translate("viewEmployee", "Find Employee"))
        self.actionFind_Next_Item.setText(_translate("viewEmployee", "Find Next Employee"))
        self.actionReport.setText(_translate("viewEmployee", "Report"))
        self.actionImport_Items_From_CSV.setText(_translate("viewEmployee", "Import Items from CSV"))
        self.actionClose.setText(_translate("viewEmployee", "Close"))
        self.actionHelp_Contents.setText(_translate("viewEmployee", "Help Contents"))
        self.actionContact_Software_Developer.setText(_translate("viewEmployee", "Contact Software Developer"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    viewEmployee = QtWidgets.QMainWindow()
    ui = Ui_viewEmployee()
    ui.setupUi(viewEmployee)
    viewEmployee.show()
    sys.exit(app.exec_())
